# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ANSWER',
            fields=[
                ('ANSWER_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('ANSWER', models.CharField(max_length=100000)),
                ('TIMESTAMP', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EVENT',
            fields=[
                ('EVENT_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=100)),
                ('DESCRIPTION', models.CharField(max_length=1000)),
                ('REGISTRATION_OPEN_DATE', models.DateField(blank=True, null=True)),
                ('REGISTRATION_CLOSE_DATE', models.DateField(blank=True, null=True)),
                ('EVENT_DATE_1', models.DateField(blank=True, null=True)),
                ('EVENT_DATE_2', models.DateField(blank=True, null=True)),
                ('DETAILS', models.CharField(max_length=50000)),
                ('WEBSITE', models.CharField(max_length=200)),
                ('LOCATION', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EXPERIENCE',
            fields=[
                ('EXPERIENCE_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('EXPERIENCE', models.CharField(max_length=100000)),
                ('TIMESTAMP', models.DateField(blank=True, null=True)),
                ('EVENT_KEY', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moonshot.EVENT')),
            ],
        ),
        migrations.CreateModel(
            name='GUIDE_AVAILABLE',
            fields=[
                ('GUIDE_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('EVENT_KEY', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moonshot.EVENT')),
            ],
        ),
        migrations.CreateModel(
            name='QUESTION',
            fields=[
                ('QUESTION_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('QUSETION', models.CharField(max_length=1000)),
                ('DESCRIPTION', models.CharField(max_length=1000)),
                ('TIMESTAMP', models.DateField(blank=True, null=True)),
                ('EVENT_KEY', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moonshot.EVENT')),
            ],
        ),
        migrations.CreateModel(
            name='TAG',
            fields=[
                ('TAG_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TAGGED_EVENT',
            fields=[
                ('RELATION_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('EVENT_KEY', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moonshot.EVENT')),
                ('TAG_KEY', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moonshot.TAG')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='EVENT_KEY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moonshot.EVENT'),
        ),
        migrations.AddField(
            model_name='answer',
            name='QUESTION_KEY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moonshot.QUESTION'),
        ),
    ]
