# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moonshot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='NUM_UPVOTES',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='NUM_UPVOTES',
        ),
    ]
