# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 16:38
from __future__ import unicode_literals
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('Moonshot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GOING_EVENT',
            fields=[
                ('GOING_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('EVENT_KEY', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moonshot.EVENT')),
            ],
        ),
        migrations.CreateModel(
            name='UPVOTE_ANSWER',
            fields=[
                ('UPVOTE_ANSWER_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('ANSWER_KEY', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moonshot.ANSWER')),
            ],
        ),
        migrations.CreateModel(
            name='UPVOTE_EXPERIENCE',
            fields=[
                ('UPVOTE_EXPERIENCE_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('EXPERIENCE_KEY', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moonshot.EXPERIENCE')),
            ],
        ),
        migrations.CreateModel(
            name='UPVOTE_GUIDE',
            fields=[
                ('UPVOTE_GUIDE_ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('USER_REF', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='USER', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('NAME', models.CharField(max_length=100)),
                ('PROFILE_LINK', models.CharField(max_length=100)),
                ('EXPERIENCE_UPVOTE', models.IntegerField()),
                ('ANSWER_UPVOTE', models.IntegerField()),
                ('GUIDE_UPVOTE', models.IntegerField()),
                ('NUM_QUESTION_ASKED', models.IntegerField()),
                ('BADGE1', models.BooleanField(default=False)),
                ('BADGE2', models.BooleanField(default=False)),
                ('BADGE3', models.BooleanField(default=False)),
                ('BADGE4', models.BooleanField(default=False)),
                ('BADGE5', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='upvote_guide',
            name='GUIDE_KEY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='Moonshot.USER'),
        ),
        migrations.AddField(
            model_name='upvote_guide',
            name='USER_KEY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guided', to='Moonshot.USER'),
        ),
        migrations.AddField(
            model_name='upvote_experience',
            name='USER_KEY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moonshot.USER'),
        ),
        migrations.AddField(
            model_name='upvote_answer',
            name='USER_KEY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moonshot.USER'),
        ),
        migrations.AddField(
            model_name='going_event',
            name='USER_KEY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moonshot.USER'),
        ),
        migrations.AddField(
            model_name='answer',
            name='USER_KEY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moonshot.USER'),
        ),
        migrations.AddField(
            model_name='event',
            name='USER_KEY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moonshot.USER'),
        ),
        migrations.AddField(
            model_name='experience',
            name='USER_KEY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moonshot.USER'),
        ),
        migrations.AddField(
            model_name='guide_available',
            name='USER_KEY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moonshot.USER'),
        ),
        migrations.AddField(
            model_name='question',
            name='USER_KEY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moonshot.USER'),
        ),
    ]
