# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Moonshot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='QUSETION',
            new_name='QUESTION',
        ),
        migrations.AlterField(
            model_name='answer',
            name='TIMESTAMP',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='EVENT_DATE_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='EVENT_DATE_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='REGISTRATION_CLOSE_DATE',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='REGISTRATION_OPEN_DATE',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='TIMESTAMP',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='going_event',
            name='GOING_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guide_available',
            name='GUIDE_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='live_chat',
            name='RECEIVER_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Moonshot.GUIDE_AVAILABLE'),
        ),
        migrations.AlterField(
            model_name='live_chat',
            name='TIMESTAMP',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='TIMESTAMP',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upvote_answer',
            name='UPVOTE_ANSWER_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upvote_experience',
            name='UPVOTE_EXPERIENCE_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
