# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Moonshot', '0002_auto_20180215_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='LIVE_CHAT',
            fields=[
                ('CHAT_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('TIMESTAMP', models.DateField(blank=True, null=True)),
                ('MESSAGE', models.CharField(max_length=1000)),
                ('RECEIVER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Moonshot.USER')),
                ('SENDER_KEY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Moonshot.USER')),
            ],
        ),
    ]
