# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moonshot', '0002_auto_20180219_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='NUM_UPVOTES',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='NUM_UPVOTES',
            field=models.IntegerField(default=0),
        ),
    ]
