# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Moonshot', '0003_live_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_chat',
            name='RECEIVER_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Moonshot.USER'),
        ),
        migrations.AlterField(
            model_name='live_chat',
            name='TIMESTAMP',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
