# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moonshot', '0003_auto_20180219_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='QUSETION',
            new_name='QUESTION',
        ),
    ]
