# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moonshot', '0004_auto_20180219_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote_experience',
            name='UPVOTE_EXPERIENCE_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
