# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moonshot', '0005_auto_20180220_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='going_event',
            name='GOING_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guide_available',
            name='GUIDE_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upvote_answer',
            name='UPVOTE_ANSWER_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
