# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moonshot', '0006_auto_20180222_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='TIMESTAMP',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='EVENT_DATE_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='EVENT_DATE_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='REGISTRATION_CLOSE_DATE',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='REGISTRATION_OPEN_DATE',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='TIMESTAMP',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='TIMESTAMP',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
