# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moonshot', '0004_auto_20180217_1149'),
        ('Moonshot', '0006_auto_20180222_0845'),
    ]

    operations = [
    ]
