# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Moonshot', '0007_merge_20180222_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='USER_ID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='going_event',
            name='GOING_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='live_chat',
            name='RECEIVER_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Moonshot.GUIDE_AVAILABLE'),
        ),
        migrations.AlterField(
            model_name='upvote_answer',
            name='UPVOTE_ANSWER_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upvote_experience',
            name='UPVOTE_EXPERIENCE_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='USER_REF',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='USER', to=settings.AUTH_USER_MODEL),
        ),
    ]
