# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 19:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Moonshot', '0008_auto_20180222_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='USER_REF',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='USER', to=settings.AUTH_USER_MODEL),
        ),
    ]
