# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moonshot', '0007_auto_20180223_0356'),
        ('Moonshot', '0010_auto_20180222_1916'),
    ]

    operations = [
    ]
